# deploy/k8s/base/network-policy.yaml

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: logistics
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-ingress
  namespace: logistics
spec:
  podSelector:
    matchLabels:
      app: gateway-svc
  policyTypes:
    - Ingress
  ingress:
    - from: []
      ports:
        - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-grpc
  namespace: logistics
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: logistics
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: logistics
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-scrape
  namespace: logistics
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - port: 8052
        - port: 8053
        - port: 8054
        - port: 8055
        - port: 8056
        - port: 8057
        - port: 8059
        - port: 8080
        - port: 8088
