# deploy/k8s/base/pod-disruption-budget.yaml

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: logistics
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: gateway-svc
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: solver-pdb
  namespace: logistics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: solver-svc
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-pdb
  namespace: logistics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-svc
